# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0002_auto_20180516_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='warninglog',
            old_name='correlationtask',
            new_name='correlationbus',
        ),
    ]
