# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0003_auto_20180516_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='agentstatu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='warninglog',
            name='type',
            field=models.IntegerField(null=True),
        ),
    ]
