# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-16 07:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0004_auto_20180516_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='ping',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
