# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-07 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0005_equipment_ping'),
    ]

    operations = [
        migrations.CreateModel(
            name='netequipmentport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('indexnum', models.IntegerField(null=True)),
                ('portindex', models.CharField(max_length=50, null=True)),
                ('portname', models.CharField(max_length=100, null=True)),
                ('portfullname', models.CharField(max_length=100, null=True)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('ifInOctets', models.BigIntegerField(null=True)),
                ('ifOutOctets', models.BigIntegerField(null=True)),
                ('ifInErrors', models.BigIntegerField(null=True)),
                ('ifOutErrors', models.BigIntegerField(null=True)),
                ('ifSpeed', models.BigIntegerField(null=True)),
                ('equipmentid', models.IntegerField(null=True)),
                ('datatime', models.DateTimeField(null=True)),
                ('inuseage', models.FloatField(null=True)),
                ('outuseage', models.FloatField(null=True)),
                ('inspeed', models.FloatField(null=True)),
                ('outspeed', models.FloatField(null=True)),
                ('usetime', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'netequipmentport',
            },
        ),
    ]
