# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-07 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0006_netequipmentport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='netequipmentport',
            old_name='portname',
            new_name='potdescribe',
        ),
        migrations.RemoveField(
            model_name='netequipmentport',
            name='indexnum',
        ),
        migrations.AddField(
            model_name='netequipmentport',
            name='port',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='netequipmentport',
            name='portindex',
            field=models.IntegerField(null=True),
        ),
    ]
