# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0007_auto_20180607_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouper',
            name='branchgroup',
            field=models.IntegerField(null=True),
        ),
    ]
