# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-12 01:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jc', '0008_grouper_branchgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grouper',
            old_name='branchgroup',
            new_name='branchgrouper',
        ),
    ]
